"""Initial schema baseline

Revision ID: e0a2b0dc1c1c
Revises: 
Create Date: 2026-10-05 19:25:06.167258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a2b0dc1c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ielts_speaking_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_band', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_key'), ['key'], unique=True)

    op.create_table('database_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_backup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_backup_backup_type'), ['backup_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_backup_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_backup_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_backup_filename'), ['filename'], unique=True)

    op.create_table('ielts_speaking_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('overall_band', sa.Float(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=False),
    sa.Column('lexical_score', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('pronunciation_score', sa.Float(), nullable=False),
    sa.Column('examiner_feedback', sa.Text(), nullable=True),
    sa.Column('detailed_analysis', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['ielts_speaking_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ielts_speaking_submission', schema=None) as batch_op:
        batch_op.create_index('idx_ielts_speaking_sub_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ielts_speaking_submission_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ielts_speaking_submission_user_id'), ['user_id'], unique=False)

    op.create_table('ielts_speaking_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(length=255), nullable=False),
    sa.Column('cue_card_prompt', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('prep_time_seconds', sa.Integer(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['ielts_speaking_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ielts_speaking_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ielts_speaking_topic_part'), ['part'], unique=False)
        batch_op.create_index(batch_op.f('ix_ielts_speaking_topic_test_id'), ['test_id'], unique=False)

    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_history_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_history_file_type'), ['file_type'], unique=False)

    op.create_table('lesson_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('draft_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', 'draft_type', name='uq_user_lesson_draft_type')
    )
    with op.batch_alter_table('lesson_draft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_draft_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_draft_user_id'), ['user_id'], unique=False)

    op.create_table('ielts_speaking_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('candidate_transcript', sa.Text(), nullable=True),
    sa.Column('audio_data_url', sa.Text(), nullable=True),
    sa.Column('candidate_notes', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['ielts_speaking_submission.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['ielts_speaking_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ielts_speaking_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ielts_speaking_answer_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ielts_speaking_answer_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('exam_submission', schema=None) as batch_op:
        batch_op.create_index('idx_exam_sub_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_set_share_code'), ['share_code'], unique=True)

    with op.batch_alter_table('grammar_topic', schema=None) as batch_op:
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_grammar_topic_order_index'), ['order_index'], unique=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_url_uk', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_attempt_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('toeic_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_toeic_attempt_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_goal_reminder_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('daily_goal_reminder_time', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('daily_goal_reminder_email', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('daily_goal_reminder_popup', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_daily_goal_reminder_date', sa.Date(), nullable=True))
        batch_op.alter_column('streak_freeze_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('vocab_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('vocab_reminder_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'09:00'::character varying"))

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'cefr'::character varying"))
        batch_op.create_index(batch_op.f('ix_vocabulary_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_lesson_unit'), ['lesson_unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_subcategory'), ['subcategory'], unique=False)

    with op.batch_alter_table('vocabulary_progress', schema=None) as batch_op:
        batch_op.create_index('idx_vocab_prog_srs', ['user_id', 'is_skipped', 'next_review_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_vocab_prog_srs')

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_subcategory'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_lesson_unit'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_category'))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cefr'::character varying"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('vocab_reminder_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'09:00'::character varying"))
        batch_op.alter_column('vocab_reminder_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('streak_freeze_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('last_daily_goal_reminder_date')
        batch_op.drop_column('daily_goal_reminder_popup')
        batch_op.drop_column('daily_goal_reminder_email')
        batch_op.drop_column('daily_goal_reminder_time')
        batch_op.drop_column('daily_goal_reminder_enabled')

    with op.batch_alter_table('toeic_attempt', schema=None) as batch_op:
        batch_op.drop_index('idx_toeic_attempt_user_created')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_index('idx_quiz_attempt_user_created')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('audio_url_uk')
        batch_op.drop_column('audio_url')

    with op.batch_alter_table('grammar_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_topic_order_index'))
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_set_share_code'))

    with op.batch_alter_table('exam_submission', schema=None) as batch_op:
        batch_op.drop_index('idx_exam_sub_user_created')

    with op.batch_alter_table('ielts_speaking_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_answer_topic_id'))
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_answer_submission_id'))

    op.drop_table('ielts_speaking_answer')
    with op.batch_alter_table('lesson_draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_draft_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_draft_lesson_id'))

    op.drop_table('lesson_draft')
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_history_file_type'))
        batch_op.drop_index(batch_op.f('ix_import_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_import_history_admin_id'))

    op.drop_table('import_history')
    with op.batch_alter_table('ielts_speaking_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_topic_test_id'))
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_topic_part'))

    op.drop_table('ielts_speaking_topic')
    with op.batch_alter_table('ielts_speaking_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_ielts_speaking_submission_test_id'))
        batch_op.drop_index('idx_ielts_speaking_sub_user_created')

    op.drop_table('ielts_speaking_submission')
    with op.batch_alter_table('database_backup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_backup_filename'))
        batch_op.drop_index(batch_op.f('ix_database_backup_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_database_backup_created_at'))
        batch_op.drop_index(batch_op.f('ix_database_backup_backup_type'))

    op.drop_table('database_backup')
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_key'))

    op.drop_table('system_setting')
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))

    op.drop_table('system_config')
    op.drop_table('ielts_speaking_test')
    # ### end Alembic commands ###
